import type { Metadata } from "next";
import { Inter, Lexend } from "next/font/google";
import "./globals.css";
import HeaderSection from "@/ui/Header";
import FooterSection from "@/ui/Footer";

const inter = Inter({
  variable: "--font-body",
  subsets: ["latin"],
});

const lexend = Lexend({
  variable: "--font-heading",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark" style={{colorScheme: "dark"}}>
      <body
        className={`${inter.variable} ${lexend.variable} antialiased`}
      >
        <HeaderSection />
        {children}
        <FooterSection />
      </body>
    </html>
  );
}
